name: Android CI

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Upload
      uses: actions/upload-artifact@v4.6.0
      with:
         name: output
         path: app/build/outputs/apk/release/app-release.apk
         if-no-files-found: error
         retention-days: 7
       
